/**
 * Illustrative demo data for the WoCOS HR frontend prototype.
 * Organization: TeamAce. All figures are demonstrative, not operational.
 */

export const DEMO_LABEL = "Illustrative Demo Data";

export const org = {
  name: "TeamAce",
  product: "WoCOS HR",
  today: "14 Sep 2026",
  clock: "09:42 WAT",
};

export const currentUser = {
  name: "Sonia Okafor",
  initials: "SO",
  role: "HR Manager",
  roleId: "hr_manager",
};

export const metrics = {
  total_workforce: 186,
  open_vacancies: 14,
  candidates_in_pipeline: 47,
  interviews_today: 5,
  verification_pending: 8,
  employees_onboarding: 11,
  deployment_ready: 7,
  active_deployments: 172,
  payroll_exceptions: 6,
  open_hr_requests: 19,
  compliance_alerts: 9,
  contracts_expiring: 12,
};

export const lifecycle = [
  { order: 1, id: "request", label: "Request", state: "done", count: 18 },
  { order: 2, id: "vacancy", label: "Vacancy", state: "done", count: 14 },
  { order: 3, id: "sourcing", label: "Sourcing", state: "done", count: 34 },
  { order: 4, id: "screening", label: "Screening", state: "done", count: 24 },
  { order: 5, id: "interview", label: "Interview", state: "done", count: 17 },
  { order: 6, id: "selection", label: "Selection", state: "done", count: 11 },
  { order: 7, id: "verification", label: "Verify", state: "active", count: 8 },
  { order: 8, id: "offer", label: "Offer", state: "queued", count: 5 },
  { order: 9, id: "onboarding", label: "Onboard", state: "queued", count: 11 },
  { order: 10, id: "compliance_check", label: "Compliance", state: "queued", count: 9 },
  { order: 11, id: "deployment_ready", label: "Ready", state: "queued", count: 7 },
  { order: 12, id: "activation", label: "Activate", state: "queued", count: 6 },
  { order: 13, id: "deployment", label: "Deploy", state: "queued", count: 172 },
  { order: 14, id: "workforce_management", label: "Manage", state: "queued", count: 186 },
  { order: 15, id: "performance", label: "Performance", state: "queued", count: 52 },
  { order: 16, id: "renewal_exit", label: "Renew / Exit", state: "queued", count: 12 },
] as const;

export const clients = [
  { name: "Nexa Logistics", headcount: 68, vacancies: 4, locations: ["Lagos", "Ibadan"] },
  { name: "ABC Company", headcount: 48, vacancies: 3, locations: ["Lagos"] },
  { name: "Kestrel Payroll", headcount: 39, vacancies: 2, locations: ["Abuja"] },
  { name: "Bluewave Retail", headcount: 27, vacancies: 3, locations: ["Lagos", "Port Harcourt"] },
  { name: "Harbor Foods", headcount: 16, vacancies: 1, locations: ["Ibadan"] },
  { name: "Solara Energy", headcount: 12, vacancies: 1, locations: ["Port Harcourt"] },
];

export const locations = [
  { name: "Lagos", headcount: 96 },
  { name: "Abuja", headcount: 38 },
  { name: "Ibadan", headcount: 24 },
  { name: "Port Harcourt", headcount: 19 },
  { name: "Remote", headcount: 9 },
];

export const pipelineFunnel = [
  { stage: "Sourcing", short: "Src", count: 34 },
  { stage: "Screening", short: "Scr", count: 24 },
  { stage: "Shortlisted", short: "Shrt", count: 17 },
  { stage: "Interview", short: "Int", count: 11 },
  { stage: "Selection", short: "Sel", count: 7 },
  { stage: "Verification", short: "Ver", count: 5 },
  { stage: "Offer", short: "Ofr", count: 3 },
];

export const hiringTrend = [
  { month: "Apr", hires: 9 },
  { month: "May", hires: 14 },
  { month: "Jun", hires: 11 },
  { month: "Jul", hires: 18 },
  { month: "Aug", hires: 16 },
  { month: "Sep", hires: 22 },
];

export const pendingApprovals = [
  { title: "Offer · Sarah Adeyemi", meta: "ABC Company", status: "awaiting_approval" },
  { title: "Readiness · 3 field technicians", meta: "Nexa Logistics", status: "under_review" },
  { title: "Timesheet batch · September", meta: "Kestrel Payroll", status: "pending_approval" },
  { title: "Leave · 2 requests", meta: "Bluewave Retail", status: "draft" },
  { title: "Workforce request WR-2041", meta: "Solara Energy", status: "submitted" },
];

export const attentionRequired = [
  {
    title: "Verification exception · T. Balogun",
    meta: "employment check failed · escalate",
    tone: "danger" as const,
  },
  { title: "Onboarding blocked · 2 candidates", meta: "missing bank details", tone: "danger" as const },
  { title: "12 contracts expiring in 14 days", meta: "compliance schedule", tone: "warning" as const },
  { title: "HR request overdue · 3 items", meta: "auto-escalated to HR Manager", tone: "warning" as const },
];

export const recentActivity = [
  { time: "09:38", text: "Sarah Adeyemi marked ready for deployment", actor: "System" },
  { time: "09:12", text: "Verification cleared for Emeka Nwosu", actor: "V. Officer" },
  { time: "08:55", text: "Vacancy VAC-118 published for Nexa Logistics", actor: "Recruiter" },
  { time: "08:40", text: "Workforce request WR-2041 submitted", actor: "Client · Solara" },
  { time: "08:21", text: "Offer sent to Ifeoma Chukwu", actor: "HR Admin" },
];

export const soniaBrief = [
  "7 candidates are cleared and ready for deployment — 3 can start Monday. Focus on the 8 pending verifications to keep the pipeline moving.",
  "Nexa Logistics is your largest active client at 68 deployed. 12 of their contracts expire within 14 days.",
  "6 payroll inputs are in exception, 2 of them critical. Timesheet approvals for Kestrel Payroll are the blocker.",
];

export const soniaPrompts = [
  "What requires my attention today?",
  "Which candidates are awaiting verification?",
  "Show employees whose onboarding is incomplete.",
  "Who is ready for deployment?",
  "Why are some employees not deployment-ready?",
  "Which client has the most open vacancies?",
  "Which contracts expire within the next 30 days?",
  "Summarize unresolved payroll issues.",
  "Which HR requests are overdue?",
  "Prepare today's HR management briefing.",
];

export const workforceRequests = [
  {
    id: "WR-2041",
    client: "Solara Energy",
    title: "Field Safety Officer",
    quantity: 2,
    location: "Port Harcourt",
    employment_type: "Full-time",
    priority: "high",
    recruiter: "Adaeze U.",
    target_start: "2026-10-05",
    status: "submitted",
    salary_budget: "₦480,000 / mo",
    experience: "4-6 years",
    skills: ["HSE Level 3", "Incident reporting", "Site audits"],
  },
  {
    id: "WR-2039",
    client: "Nexa Logistics",
    title: "Warehouse Supervisor",
    quantity: 4,
    location: "Lagos",
    employment_type: "Full-time",
    priority: "critical",
    recruiter: "Tunde A.",
    target_start: "2026-09-28",
    status: "recruiting",
    salary_budget: "₦390,000 / mo",
    experience: "3-5 years",
    skills: ["Inventory control", "Team leadership", "WMS"],
  },
  {
    id: "WR-2036",
    client: "ABC Company",
    title: "Customer Service Executive",
    quantity: 6,
    location: "Lagos",
    employment_type: "Full-time",
    priority: "medium",
    recruiter: "Adaeze U.",
    target_start: "2026-09-28",
    status: "partially_filled",
    salary_budget: "₦280,000 / mo",
    experience: "1-3 years",
    skills: ["CRM", "Communication", "Complaint handling"],
  },
  {
    id: "WR-2032",
    client: "Kestrel Payroll",
    title: "Payroll Assistant",
    quantity: 2,
    location: "Abuja",
    employment_type: "Contract",
    priority: "medium",
    recruiter: "Bola K.",
    target_start: "2026-10-12",
    status: "approved",
    salary_budget: "₦320,000 / mo",
    experience: "2-4 years",
    skills: ["Payroll inputs", "Excel", "Statutory filings"],
  },
  {
    id: "WR-2028",
    client: "Bluewave Retail",
    title: "Store Associate",
    quantity: 8,
    location: "Port Harcourt",
    employment_type: "Part-time",
    priority: "low",
    recruiter: "Tunde A.",
    target_start: "2026-11-02",
    status: "under_review",
    salary_budget: "₦180,000 / mo",
    experience: "0-2 years",
    skills: ["POS", "Merchandising"],
  },
  {
    id: "WR-2019",
    client: "Harbor Foods",
    title: "Quality Inspector",
    quantity: 3,
    location: "Ibadan",
    employment_type: "Full-time",
    priority: "medium",
    recruiter: "Bola K.",
    target_start: "2026-09-21",
    status: "filled",
    salary_budget: "₦300,000 / mo",
    experience: "2-5 years",
    skills: ["HACCP", "Sampling", "Documentation"],
  },
  {
    id: "WR-2044",
    client: "Nexa Logistics",
    title: "Fleet Coordinator",
    quantity: 1,
    location: "Ibadan",
    employment_type: "Full-time",
    priority: "high",
    recruiter: "—",
    target_start: "2026-10-19",
    status: "draft",
    salary_budget: "₦350,000 / mo",
    experience: "3-5 years",
    skills: ["Route planning", "Telematics"],
  },
];

export const vacancies = [
  {
    id: "VAC-118",
    title: "Warehouse Supervisor",
    client: "Nexa Logistics",
    location: "Lagos",
    required: 4,
    applications: 38,
    screened: 22,
    shortlisted: 11,
    interviewed: 6,
    selected: 2,
    filled: 1,
    status: "active",
    recruiter: "Tunde A.",
    opened: "2026-08-24",
  },
  {
    id: "VAC-116",
    title: "Customer Service Executive",
    client: "ABC Company",
    location: "Lagos",
    required: 6,
    applications: 74,
    screened: 51,
    shortlisted: 24,
    interviewed: 14,
    selected: 5,
    filled: 3,
    status: "active",
    recruiter: "Adaeze U.",
    opened: "2026-08-11",
  },
  {
    id: "VAC-114",
    title: "Payroll Assistant",
    client: "Kestrel Payroll",
    location: "Abuja",
    required: 2,
    applications: 29,
    screened: 18,
    shortlisted: 7,
    interviewed: 4,
    selected: 1,
    filled: 0,
    status: "active",
    recruiter: "Bola K.",
    opened: "2026-09-01",
  },
  {
    id: "VAC-111",
    title: "Store Associate",
    client: "Bluewave Retail",
    location: "Port Harcourt",
    required: 8,
    applications: 96,
    screened: 60,
    shortlisted: 28,
    interviewed: 12,
    selected: 4,
    filled: 4,
    status: "paused",
    recruiter: "Tunde A.",
    opened: "2026-07-19",
  },
  {
    id: "VAC-108",
    title: "Quality Inspector",
    client: "Harbor Foods",
    location: "Ibadan",
    required: 3,
    applications: 41,
    screened: 26,
    shortlisted: 12,
    interviewed: 8,
    selected: 3,
    filled: 3,
    status: "filled",
    recruiter: "Bola K.",
    opened: "2026-07-02",
  },
  {
    id: "VAC-120",
    title: "Field Safety Officer",
    client: "Solara Energy",
    location: "Port Harcourt",
    required: 2,
    applications: 6,
    screened: 2,
    shortlisted: 0,
    interviewed: 0,
    selected: 0,
    filled: 0,
    status: "draft",
    recruiter: "Adaeze U.",
    opened: "2026-09-13",
  },
];

export type Candidate = {
  id: string;
  name: string;
  initials: string;
  role: string;
  client: string;
  location: string;
  experience: string;
  education: string;
  skills: string[];
  source: string;
  recruiter: string;
  stage: string;
  score?: number;
  email: string;
  phone: string;
  applied: string;
};

export const candidatePipeline = [
  "applied",
  "screening",
  "shortlisted",
  "interview",
  "assessment",
  "client_review",
  "selected",
  "verification",
  "offer",
  "onboarding",
];

export const candidates: Candidate[] = [
  {
    id: "CAN-4412",
    name: "Sarah Adeyemi",
    initials: "SA",
    role: "Customer Service Executive",
    client: "ABC Company",
    location: "Lagos",
    experience: "4 years",
    education: "BSc Mass Communication, UNILAG",
    skills: ["CRM", "Complaint handling", "Voice support", "Zendesk"],
    source: "Referral",
    recruiter: "Adaeze U.",
    stage: "onboarding",
    score: 92,
    email: "sarah.adeyemi@example.com",
    phone: "+234 803 555 0142",
    applied: "2026-08-14",
  },
  {
    id: "CAN-4407",
    name: "Emeka Nwosu",
    initials: "EN",
    role: "Warehouse Supervisor",
    client: "Nexa Logistics",
    location: "Lagos",
    experience: "6 years",
    education: "HND Logistics, YABATECH",
    skills: ["WMS", "Inventory", "Team lead"],
    source: "Job board",
    recruiter: "Tunde A.",
    stage: "offer",
    score: 88,
    email: "emeka.nwosu@example.com",
    phone: "+234 806 555 0198",
    applied: "2026-08-19",
  },
  {
    id: "CAN-4401",
    name: "Ifeoma Chukwu",
    initials: "IC",
    role: "Payroll Assistant",
    client: "Kestrel Payroll",
    location: "Abuja",
    experience: "3 years",
    education: "BSc Accounting, UNN",
    skills: ["Payroll inputs", "Excel", "PAYE"],
    source: "Agency",
    recruiter: "Bola K.",
    stage: "verification",
    score: 84,
    email: "ifeoma.chukwu@example.com",
    phone: "+234 811 555 0177",
    applied: "2026-08-22",
  },
  {
    id: "CAN-4398",
    name: "Tobi Balogun",
    initials: "TB",
    role: "Warehouse Supervisor",
    client: "Nexa Logistics",
    location: "Ibadan",
    experience: "5 years",
    education: "BSc Business Admin, OAU",
    skills: ["Inventory", "Safety", "Scheduling"],
    source: "Job board",
    recruiter: "Tunde A.",
    stage: "verification",
    score: 71,
    email: "tobi.balogun@example.com",
    phone: "+234 802 555 0110",
    applied: "2026-08-25",
  },
  {
    id: "CAN-4392",
    name: "Aisha Bello",
    initials: "AB",
    role: "Customer Service Executive",
    client: "ABC Company",
    location: "Lagos",
    experience: "2 years",
    education: "BA English, BUK",
    skills: ["CRM", "Email support"],
    source: "Career site",
    recruiter: "Adaeze U.",
    stage: "selected",
    score: 86,
    email: "aisha.bello@example.com",
    phone: "+234 809 555 0163",
    applied: "2026-08-28",
  },
  {
    id: "CAN-4388",
    name: "Chinedu Okafor",
    initials: "CO",
    role: "Field Safety Officer",
    client: "Solara Energy",
    location: "Port Harcourt",
    experience: "7 years",
    education: "BEng Chemical, UNIPORT",
    skills: ["HSE Level 3", "Audits", "Permits"],
    source: "Referral",
    recruiter: "Adaeze U.",
    stage: "client_review",
    score: 90,
    email: "chinedu.okafor@example.com",
    phone: "+234 703 555 0121",
    applied: "2026-09-01",
  },
  {
    id: "CAN-4381",
    name: "Ngozi Eze",
    initials: "NE",
    role: "Store Associate",
    client: "Bluewave Retail",
    location: "Port Harcourt",
    experience: "1 year",
    education: "OND Marketing",
    skills: ["POS", "Merchandising"],
    source: "Walk-in",
    recruiter: "Tunde A.",
    stage: "assessment",
    score: 74,
    email: "ngozi.eze@example.com",
    phone: "+234 805 555 0134",
    applied: "2026-09-02",
  },
  {
    id: "CAN-4377",
    name: "Yusuf Ibrahim",
    initials: "YI",
    role: "Quality Inspector",
    client: "Harbor Foods",
    location: "Ibadan",
    experience: "4 years",
    education: "BSc Food Science, FUTA",
    skills: ["HACCP", "Sampling"],
    source: "Job board",
    recruiter: "Bola K.",
    stage: "interview",
    score: 81,
    email: "yusuf.ibrahim@example.com",
    phone: "+234 807 555 0188",
    applied: "2026-09-04",
  },
  {
    id: "CAN-4372",
    name: "Blessing Ojo",
    initials: "BO",
    role: "Customer Service Executive",
    client: "ABC Company",
    location: "Lagos",
    experience: "3 years",
    education: "BSc Sociology, UI",
    skills: ["CRM", "Retention"],
    source: "Career site",
    recruiter: "Adaeze U.",
    stage: "shortlisted",
    score: 79,
    email: "blessing.ojo@example.com",
    phone: "+234 813 555 0155",
    applied: "2026-09-06",
  },
  {
    id: "CAN-4369",
    name: "Kelechi Obi",
    initials: "KO",
    role: "Payroll Assistant",
    client: "Kestrel Payroll",
    location: "Abuja",
    experience: "2 years",
    education: "BSc Economics, ABU",
    skills: ["Excel", "Reconciliation"],
    source: "Agency",
    recruiter: "Bola K.",
    stage: "screening",
    score: 68,
    email: "kelechi.obi@example.com",
    phone: "+234 814 555 0102",
    applied: "2026-09-08",
  },
  {
    id: "CAN-4365",
    name: "Fatima Sani",
    initials: "FS",
    role: "Store Associate",
    client: "Bluewave Retail",
    location: "Lagos",
    experience: "1 year",
    education: "SSCE",
    skills: ["POS"],
    source: "Walk-in",
    recruiter: "Tunde A.",
    stage: "applied",
    email: "fatima.sani@example.com",
    phone: "+234 816 555 0119",
    applied: "2026-09-11",
  },
  {
    id: "CAN-4362",
    name: "Segun Adeleke",
    initials: "SA",
    role: "Fleet Coordinator",
    client: "Nexa Logistics",
    location: "Ibadan",
    experience: "5 years",
    education: "HND Transport Mgmt",
    skills: ["Route planning", "Telematics"],
    source: "Referral",
    recruiter: "Tunde A.",
    stage: "applied",
    email: "segun.adeleke@example.com",
    phone: "+234 818 555 0146",
    applied: "2026-09-12",
  },
];

export const interviews = [
  {
    candidate: "Yusuf Ibrahim",
    vacancy: "Quality Inspector · Harbor Foods",
    interviewer: "Bola K. + Client panel",
    date: "2026-09-14",
    time: "10:30",
    format: "Video",
    status: "submitted",
  },
  {
    candidate: "Blessing Ojo",
    vacancy: "Customer Service Executive · ABC",
    interviewer: "Adaeze U.",
    date: "2026-09-14",
    time: "12:00",
    format: "Video",
    status: "pending",
  },
  {
    candidate: "Ngozi Eze",
    vacancy: "Store Associate · Bluewave Retail",
    interviewer: "Tunde A.",
    date: "2026-09-14",
    time: "14:00",
    format: "On-site",
    status: "pending",
  },
  {
    candidate: "Kelechi Obi",
    vacancy: "Payroll Assistant · Kestrel",
    interviewer: "Bola K.",
    date: "2026-09-14",
    time: "15:30",
    format: "Phone",
    status: "pending",
  },
  {
    candidate: "Segun Adeleke",
    vacancy: "Fleet Coordinator · Nexa Logistics",
    interviewer: "Tunde A.",
    date: "2026-09-14",
    time: "16:30",
    format: "Video",
    status: "pending",
  },
  {
    candidate: "Chinedu Okafor",
    vacancy: "Field Safety Officer · Solara",
    interviewer: "Client panel",
    date: "2026-09-15",
    time: "09:00",
    format: "On-site",
    status: "pending",
  },
  {
    candidate: "Aisha Bello",
    vacancy: "Customer Service Executive · ABC",
    interviewer: "Adaeze U.",
    date: "2026-09-11",
    time: "11:00",
    format: "Video",
    status: "approved",
  },
];

export const scorecardCriteria = [
  { id: "communication", label: "Communication", score: 5 },
  { id: "technical_competence", label: "Technical competence", score: 4 },
  { id: "experience", label: "Experience", score: 4 },
  { id: "role_fit", label: "Role fit", score: 5 },
  { id: "professionalism", label: "Professionalism", score: 4 },
];

export const verificationCases = [
  {
    id: "BV-3092",
    candidate: "Sarah Adeyemi",
    role: "Customer Service Executive",
    client: "ABC Company",
    status: "cleared",
    opened: "2026-09-02",
    checks: {
      identity: "cleared",
      education: "cleared",
      employment: "cleared",
      references: "cleared",
      address: "cleared",
      other_required_checks: "cleared",
    },
  },
  {
    id: "BV-3088",
    candidate: "Ifeoma Chukwu",
    role: "Payroll Assistant",
    client: "Kestrel Payroll",
    status: "in_progress",
    opened: "2026-09-05",
    checks: {
      identity: "cleared",
      education: "cleared",
      employment: "in_progress",
      references: "pending",
      address: "cleared",
      other_required_checks: "pending",
    },
  },
  {
    id: "BV-3085",
    candidate: "Tobi Balogun",
    role: "Warehouse Supervisor",
    client: "Nexa Logistics",
    status: "exception",
    opened: "2026-09-05",
    checks: {
      identity: "cleared",
      education: "cleared",
      employment: "failed",
      references: "in_progress",
      address: "cleared",
      other_required_checks: "pending",
    },
  },
  {
    id: "BV-3081",
    candidate: "Aisha Bello",
    role: "Customer Service Executive",
    client: "ABC Company",
    status: "awaiting_consent",
    opened: "2026-09-09",
    checks: {
      identity: "pending",
      education: "pending",
      employment: "pending",
      references: "pending",
      address: "pending",
      other_required_checks: "pending",
    },
  },
  {
    id: "BV-3078",
    candidate: "Chinedu Okafor",
    role: "Field Safety Officer",
    client: "Solara Energy",
    status: "pending",
    opened: "2026-09-10",
    checks: {
      identity: "cleared",
      education: "pending",
      employment: "pending",
      references: "pending",
      address: "in_progress",
      other_required_checks: "pending",
    },
  },
];

export const offers = [
  {
    id: "OFR-981",
    candidate: "Sarah Adeyemi",
    position: "Customer Service Executive",
    client: "ABC Company",
    salary: "₦285,000 / mo",
    employment_type: "Full-time",
    start_date: "2026-09-28",
    offer_date: "2026-09-08",
    expiry: "2026-09-18",
    status: "accepted",
  },
  {
    id: "OFR-979",
    candidate: "Emeka Nwosu",
    position: "Warehouse Supervisor",
    client: "Nexa Logistics",
    salary: "₦395,000 / mo",
    employment_type: "Full-time",
    start_date: "2026-10-01",
    offer_date: "2026-09-11",
    expiry: "2026-09-21",
    status: "sent",
  },
  {
    id: "OFR-977",
    candidate: "Aisha Bello",
    position: "Customer Service Executive",
    client: "ABC Company",
    salary: "₦270,000 / mo",
    employment_type: "Full-time",
    start_date: "2026-10-05",
    offer_date: "2026-09-12",
    expiry: "2026-09-22",
    status: "awaiting_approval",
  },
  {
    id: "OFR-974",
    candidate: "Yusuf Ibrahim",
    position: "Quality Inspector",
    client: "Harbor Foods",
    salary: "₦305,000 / mo",
    employment_type: "Full-time",
    start_date: "2026-09-21",
    offer_date: "2026-09-01",
    expiry: "2026-09-11",
    status: "expired",
  },
  {
    id: "OFR-970",
    candidate: "Kelechi Obi",
    position: "Payroll Assistant",
    client: "Kestrel Payroll",
    salary: "₦320,000 / mo",
    employment_type: "Contract",
    start_date: "2026-10-12",
    offer_date: "—",
    expiry: "—",
    status: "draft",
  },
];

export const onboardingChecklist = [
  { id: "personal_details", label: "Personal details", status: "approved" },
  { id: "identification", label: "Identification", status: "approved" },
  { id: "employment_contract", label: "Employment contract", status: "approved" },
  { id: "bank_details", label: "Bank details", status: "approved" },
  { id: "tax_information", label: "Tax information", status: "approved" },
  { id: "pension_information", label: "Pension information", status: "approved" },
  { id: "benefits_information", label: "Benefits information", status: "approved" },
  { id: "emergency_contact", label: "Emergency contact", status: "approved" },
  { id: "policy_acknowledgements", label: "Policy acknowledgements", status: "approved" },
  { id: "certifications", label: "Certifications", status: "approved" },
  { id: "client_documents", label: "Client documents", status: "approved" },
  { id: "induction", label: "Induction", status: "approved" },
];

export const onboardingCases = [
  { candidate: "Sarah Adeyemi", client: "ABC Company", start: "2026-09-28", progress: 100, status: "completed" },
  { candidate: "Emeka Nwosu", client: "Nexa Logistics", start: "2026-10-01", progress: 75, status: "in_progress" },
  { candidate: "Aisha Bello", client: "ABC Company", start: "2026-10-05", progress: 58, status: "in_progress" },
  { candidate: "Ngozi Eze", client: "Bluewave Retail", start: "2026-10-05", progress: 42, status: "blocked" },
  { candidate: "Fatima Sani", client: "Bluewave Retail", start: "2026-10-12", progress: 33, status: "blocked" },
  { candidate: "Yusuf Ibrahim", client: "Harbor Foods", start: "2026-09-21", progress: 92, status: "under_review" },
  { candidate: "Kelechi Obi", client: "Kestrel Payroll", start: "2026-10-12", progress: 17, status: "not_started" },
];

export const readinessRequirements = [
  "contract_signed",
  "identity_verified",
  "background_verification_cleared",
  "required_documents_complete",
  "bank_information_complete",
  "statutory_information_complete",
  "client_requirements_complete",
  "induction_completed",
  "deployment_location_confirmed",
  "reporting_manager_confirmed",
  "start_date_confirmed",
];

export const readinessCases = [
  {
    candidate: "Sarah Adeyemi",
    client: "ABC Company",
    location: "Lagos",
    start: "2026-09-28",
    status: "ready_for_deployment",
    met: readinessRequirements,
  },
  {
    candidate: "Emeka Nwosu",
    client: "Nexa Logistics",
    location: "Lagos",
    start: "2026-10-01",
    status: "pending_requirements",
    met: readinessRequirements.slice(0, 8),
  },
  {
    candidate: "Yusuf Ibrahim",
    client: "Harbor Foods",
    location: "Ibadan",
    start: "2026-09-21",
    status: "ready_for_deployment",
    met: readinessRequirements,
  },
  {
    candidate: "Aisha Bello",
    client: "ABC Company",
    location: "Lagos",
    start: "2026-10-05",
    status: "pending_requirements",
    met: readinessRequirements.slice(0, 5),
  },
  {
    candidate: "Ngozi Eze",
    client: "Bluewave Retail",
    location: "Port Harcourt",
    start: "2026-10-05",
    status: "not_cleared",
    met: readinessRequirements.slice(0, 3),
  },
  {
    candidate: "Chinedu Okafor",
    client: "Solara Energy",
    location: "Port Harcourt",
    start: "2026-10-19",
    status: "not_cleared",
    met: readinessRequirements.slice(0, 2),
  },
];

export const employees = [
  {
    id: "EMP-10442",
    name: "Sarah Adeyemi",
    initials: "SA",
    role: "Customer Service Executive",
    client: "ABC Company",
    location: "Lagos",
    manager: "Grace Umeh",
    start: "2026-09-28",
    status: "active",
    contract: "Full-time · 12 months",
    compliance: "compliant",
  },
  {
    id: "EMP-10388",
    name: "Daniel Aluko",
    initials: "DA",
    role: "Warehouse Supervisor",
    client: "Nexa Logistics",
    location: "Lagos",
    manager: "Peter Ndu",
    start: "2025-11-03",
    status: "active",
    contract: "Full-time · 24 months",
    compliance: "expiring",
  },
  {
    id: "EMP-10321",
    name: "Grace Umeh",
    initials: "GU",
    role: "Team Lead, Support",
    client: "ABC Company",
    location: "Lagos",
    manager: "Client supervisor",
    start: "2024-06-17",
    status: "active",
    contract: "Full-time · rolling",
    compliance: "compliant",
  },
  {
    id: "EMP-10297",
    name: "Musa Danjuma",
    initials: "MD",
    role: "Payroll Assistant",
    client: "Kestrel Payroll",
    location: "Abuja",
    manager: "Halima Yaro",
    start: "2025-02-10",
    status: "on_leave",
    contract: "Contract · 12 months",
    compliance: "compliant",
  },
  {
    id: "EMP-10255",
    name: "Chioma Nnaji",
    initials: "CN",
    role: "Store Associate",
    client: "Bluewave Retail",
    location: "Port Harcourt",
    manager: "Ebere Obi",
    start: "2025-08-01",
    status: "reassignment",
    contract: "Part-time · 6 months",
    compliance: "under_review",
  },
  {
    id: "EMP-10201",
    name: "Ahmed Lawal",
    initials: "AL",
    role: "Quality Inspector",
    client: "Harbor Foods",
    location: "Ibadan",
    manager: "Femi Ade",
    start: "2024-03-04",
    status: "exiting",
    contract: "Full-time · expiring",
    compliance: "expired",
  },
  {
    id: "EMP-10188",
    name: "Halima Yaro",
    initials: "HY",
    role: "Payroll Officer",
    client: "Kestrel Payroll",
    location: "Abuja",
    manager: "Client supervisor",
    start: "2023-10-16",
    status: "active",
    contract: "Full-time · rolling",
    compliance: "compliant",
  },
  {
    id: "EMP-10143",
    name: "Peter Ndu",
    initials: "PN",
    role: "Operations Supervisor",
    client: "Nexa Logistics",
    location: "Ibadan",
    manager: "Client supervisor",
    start: "2023-05-22",
    status: "active",
    contract: "Full-time · rolling",
    compliance: "compliant",
  },
  {
    id: "EMP-10102",
    name: "Esther Bassey",
    initials: "EB",
    role: "Field Safety Officer",
    client: "Solara Energy",
    location: "Port Harcourt",
    manager: "Client supervisor",
    start: "2024-11-11",
    status: "suspended",
    contract: "Full-time · 24 months",
    compliance: "under_review",
  },
];

export const deployments = [
  {
    employee: "Sarah Adeyemi",
    client: "ABC Company",
    department: "Customer Experience",
    location: "Lagos",
    supervisor: "Grace Umeh",
    start: "2026-09-28",
    end: "2027-09-27",
    contract: "Full-time",
    status: "ready_for_deployment",
  },
  {
    employee: "Daniel Aluko",
    client: "Nexa Logistics",
    department: "Warehouse Ops",
    location: "Lagos",
    supervisor: "Peter Ndu",
    start: "2025-11-03",
    end: "2027-11-02",
    contract: "Full-time",
    status: "deployed",
  },
  {
    employee: "Musa Danjuma",
    client: "Kestrel Payroll",
    department: "Payroll",
    location: "Abuja",
    supervisor: "Halima Yaro",
    start: "2025-02-10",
    end: "2026-02-09",
    contract: "Contract",
    status: "on_leave",
  },
  {
    employee: "Chioma Nnaji",
    client: "Bluewave Retail",
    department: "Retail Floor",
    location: "Port Harcourt",
    supervisor: "Ebere Obi",
    start: "2025-08-01",
    end: "2026-01-31",
    contract: "Part-time",
    status: "reassignment",
  },
  {
    employee: "Ahmed Lawal",
    client: "Harbor Foods",
    department: "Quality",
    location: "Ibadan",
    supervisor: "Femi Ade",
    start: "2024-03-04",
    end: "2026-09-30",
    contract: "Full-time",
    status: "exiting",
  },
  {
    employee: "Esther Bassey",
    client: "Solara Energy",
    department: "HSE",
    location: "Port Harcourt",
    supervisor: "Client supervisor",
    start: "2024-11-11",
    end: "2026-11-10",
    contract: "Full-time",
    status: "suspended",
  },
];

export const attendanceToday = {
  present: 154,
  remote: 9,
  leave: 12,
  late: 7,
  absent: 4,
  exception: 5,
};

export const attendanceRows = [
  { employee: "Daniel Aluko", client: "Nexa Logistics", in: "07:52", out: "17:04", hours: "9.2", status: "present" },
  { employee: "Grace Umeh", client: "ABC Company", in: "08:12", out: "17:01", hours: "8.8", status: "present" },
  { employee: "Chioma Nnaji", client: "Bluewave Retail", in: "09:41", out: "18:10", hours: "8.5", status: "late" },
  { employee: "Halima Yaro", client: "Kestrel Payroll", in: "—", out: "—", hours: "0.0", status: "leave" },
  { employee: "Peter Ndu", client: "Nexa Logistics", in: "07:30", out: "—", hours: "—", status: "exception" },
  { employee: "Ahmed Lawal", client: "Harbor Foods", in: "—", out: "—", hours: "0.0", status: "absent" },
  { employee: "Esther Bassey", client: "Solara Energy", in: "08:02", out: "16:40", hours: "8.1", status: "remote" },
];

export const timesheets = [
  { id: "TS-8841", employee: "Daniel Aluko", client: "Nexa Logistics", period: "01–14 Sep", hours: 88, overtime: 6, status: "pending_approval" },
  { id: "TS-8839", employee: "Grace Umeh", client: "ABC Company", period: "01–14 Sep", hours: 84, overtime: 0, status: "approved" },
  { id: "TS-8836", employee: "Chioma Nnaji", client: "Bluewave Retail", period: "01–14 Sep", hours: 56, overtime: 2, status: "rejected" },
  { id: "TS-8833", employee: "Halima Yaro", client: "Kestrel Payroll", period: "01–14 Sep", hours: 80, overtime: 4, status: "submitted" },
  { id: "TS-8829", employee: "Peter Ndu", client: "Nexa Logistics", period: "01–14 Sep", hours: 90, overtime: 10, status: "locked" },
  { id: "TS-8825", employee: "Esther Bassey", client: "Solara Energy", period: "01–14 Sep", hours: 72, overtime: 0, status: "draft" },
];

export const leaveRequests = [
  { id: "LV-612", employee: "Musa Danjuma", type: "Annual", from: "2026-09-10", to: "2026-09-24", days: 11, status: "approved" },
  { id: "LV-609", employee: "Grace Umeh", type: "Sick", from: "2026-09-15", to: "2026-09-16", days: 2, status: "hr_review" },
  { id: "LV-606", employee: "Chioma Nnaji", type: "Compassionate", from: "2026-09-18", to: "2026-09-22", days: 5, status: "manager_review" },
  { id: "LV-603", employee: "Daniel Aluko", type: "Annual", from: "2026-10-05", to: "2026-10-16", days: 10, status: "submitted" },
  { id: "LV-598", employee: "Ahmed Lawal", type: "Annual", from: "2026-09-01", to: "2026-09-05", days: 5, status: "rejected" },
  { id: "LV-594", employee: "Halima Yaro", type: "Maternity", from: "2026-11-02", to: "2027-02-01", days: 90, status: "draft" },
];

export const leaveBalances = [
  { type: "Annual", entitled: 20, taken: 11, balance: 9 },
  { type: "Sick", entitled: 10, taken: 2, balance: 8 },
  { type: "Compassionate", entitled: 5, taken: 0, balance: 5 },
  { type: "Study", entitled: 5, taken: 5, balance: 0 },
];

export const payrollStages = [
  { id: "timesheets", label: "Timesheets", status: "approved", count: 172 },
  { id: "payroll_inputs", label: "Payroll inputs", status: "ready", count: 168 },
  { id: "allowances", label: "Allowances", status: "ready", count: 141 },
  { id: "deductions", label: "Deductions", status: "exception", count: 6 },
  { id: "exception_review", label: "Exception review", status: "awaiting_approval", count: 6 },
  { id: "hr_review", label: "HR review", status: "awaiting_approval", count: 1 },
  { id: "client_approval", label: "Client approval", status: "not_ready", count: 4 },
  { id: "payroll_handoff", label: "Payroll handoff", status: "not_ready", count: 0 },
  { id: "payment_status", label: "Payment status", status: "not_ready", count: 0 },
];

export const payrollExceptions = [
  { employee: "Peter Ndu", client: "Nexa Logistics", issue: "Missing clock-out on 3 shifts", severity: "critical" },
  { employee: "Chioma Nnaji", client: "Bluewave Retail", issue: "Rejected timesheet not resubmitted", severity: "critical" },
  { employee: "Esther Bassey", client: "Solara Energy", issue: "Suspension overlap with paid days", severity: "high" },
  { employee: "Ahmed Lawal", client: "Harbor Foods", issue: "Exit date precedes period end", severity: "high" },
  { employee: "Musa Danjuma", client: "Kestrel Payroll", issue: "Leave days exceed balance", severity: "medium" },
  { employee: "Fatima Sani", client: "Bluewave Retail", issue: "Bank details unverified", severity: "medium" },
];

export const serviceDeskTickets = [
  { id: "HR-7712", employee: "Daniel Aluko", category: "payroll_issue", subject: "Overtime not reflected in August", priority: "high", status: "investigating", age: "3d" },
  { id: "HR-7708", employee: "Grace Umeh", category: "benefits", subject: "HMO card replacement", priority: "medium", status: "assigned", age: "2d" },
  { id: "HR-7705", employee: "Chioma Nnaji", category: "workplace_complaint", subject: "Shift roster fairness concern", priority: "critical", status: "open", age: "5d" },
  { id: "HR-7701", employee: "Halima Yaro", category: "document_request", subject: "Employment confirmation letter", priority: "low", status: "resolved", age: "6d" },
  { id: "HR-7699", employee: "Musa Danjuma", category: "leave", subject: "Leave balance mismatch", priority: "medium", status: "awaiting_response", age: "7d" },
  { id: "HR-7694", employee: "Peter Ndu", category: "contract", subject: "Renewal terms clarification", priority: "high", status: "open", age: "9d" },
];

export const performanceReviews = [
  { employee: "Daniel Aluko", client: "Nexa Logistics", cycle: "H2 2026", stage: "manager_review", rating: "4.2", objectives: 5, status: "under_review" },
  { employee: "Grace Umeh", client: "ABC Company", cycle: "H2 2026", stage: "final_review", rating: "4.6", objectives: 6, status: "approved" },
  { employee: "Sarah Adeyemi", client: "ABC Company", cycle: "Probation", stage: "check_in", rating: "—", objectives: 3, status: "in_progress" },
  { employee: "Chioma Nnaji", client: "Bluewave Retail", cycle: "H2 2026", stage: "employee_feedback", rating: "2.9", objectives: 4, status: "under_review" },
  { employee: "Peter Ndu", client: "Nexa Logistics", cycle: "H2 2026", stage: "development_plan", rating: "4.4", objectives: 6, status: "completed" },
];

export const complianceItems = [
  { category: "employment_contracts", item: "Contract renewal · Daniel Aluko", expires: "2026-09-24", status: "expiring" },
  { category: "identity_documents", item: "NIN verification · Fatima Sani", expires: "—", status: "missing" },
  { category: "certifications", item: "HSE Level 3 · Esther Bassey", expires: "2026-09-30", status: "expiring" },
  { category: "tax", item: "PAYE registration · Kelechi Obi", expires: "—", status: "under_review" },
  { category: "pension", item: "RSA PIN · Ngozi Eze", expires: "—", status: "missing" },
  { category: "health_benefits", item: "HMO enrolment · Ahmed Lawal", expires: "2026-09-08", status: "expired" },
  { category: "background_checks", item: "Employment check · Tobi Balogun", expires: "—", status: "under_review" },
  { category: "client_requirements", item: "Site induction · Nexa Logistics batch", expires: "2026-10-14", status: "compliant" },
];

export const complianceAlertWindows = [
  { window: "Expired", count: 3, tone: "danger" as const },
  { window: "7 days", count: 2, tone: "danger" as const },
  { window: "14 days", count: 4, tone: "warning" as const },
  { window: "30 days", count: 12, tone: "warning" as const },
];

export const analyticsCategories = {
  recruitment: [
    { label: "Applications", value: "284", delta: "+18%" },
    { label: "Time to fill", value: "24 d", delta: "-3 d" },
    { label: "Screening conversion", value: "62%", delta: "+4%" },
    { label: "Interview conversion", value: "41%", delta: "+2%" },
    { label: "Offer acceptance", value: "88%", delta: "+6%" },
  ],
  workforce: [
    { label: "Headcount", value: "186", delta: "+6" },
    { label: "Workforce by client", value: "6 clients", delta: "—" },
    { label: "Workforce by location", value: "5 sites", delta: "—" },
    { label: "Turnover", value: "7.4%", delta: "-1.1%" },
    { label: "Absenteeism", value: "2.1%", delta: "+0.3%" },
  ],
  operations: [
    { label: "Onboarding completion", value: "81%", delta: "+5%" },
    { label: "Open HR cases", value: "19", delta: "-4" },
    { label: "Case resolution time", value: "2.6 d", delta: "-0.4 d" },
    { label: "Deployment readiness", value: "7 ready", delta: "+3" },
  ],
  compliance: [
    { label: "Compliance rate", value: "94%", delta: "+2%" },
    { label: "Expiring documents", value: "12", delta: "+3" },
    { label: "Expired documents", value: "3", delta: "-1" },
  ],
  payroll: [
    { label: "Payroll readiness", value: "91%", delta: "+7%" },
    { label: "Exceptions", value: "6", delta: "-2" },
    { label: "Approval status", value: "Awaiting HR", delta: "—" },
  ],
};

export const configurableItems = [
  { id: "recruitment_stages", label: "Recruitment stages", detail: "10 stages · 2 client gates", status: "active" },
  { id: "interview_templates", label: "Interview templates", detail: "6 templates", status: "active" },
  { id: "scorecards", label: "Scorecards", detail: "5 criteria · 4 recommendations", status: "active" },
  { id: "verification_types", label: "Verification types", detail: "6 check types", status: "active" },
  { id: "onboarding_checklists", label: "Onboarding checklists", detail: "12 items · 3 client variants", status: "active" },
  { id: "deployment_requirements", label: "Deployment requirements", detail: "11 required items", status: "active" },
  { id: "employee_fields", label: "Employee fields", detail: "42 fields · 8 custom", status: "active" },
  { id: "leave_types", label: "Leave types", detail: "6 types", status: "active" },
  { id: "approval_chains", label: "Approval chains", detail: "9 chains", status: "under_review" },
  { id: "hr_request_categories", label: "HR request categories", detail: "8 categories", status: "active" },
  { id: "compliance_requirements", label: "Compliance requirements", detail: "8 categories", status: "active" },
  { id: "client_requirements", label: "Client requirements", detail: "6 client profiles", status: "active" },
  { id: "notifications", label: "Notifications", detail: "23 templates", status: "active" },
  { id: "roles", label: "Roles", detail: "10 roles", status: "active" },
  { id: "permissions", label: "Permissions", detail: "84 permission flags", status: "under_review" },
];

export const automationTriggers = [
  { event: "workforce_request_approved", action: "create_vacancy", status: "active" },
  { event: "candidate_shortlisted", action: "enable_interview_scheduling", status: "active" },
  { event: "candidate_selected", action: "create_verification_case", status: "active" },
  { event: "verification_cleared", action: "enable_offer_generation", status: "active" },
  { event: "offer_accepted", action: "create_onboarding_case", status: "active" },
  { event: "onboarding_completed", action: "run_deployment_readiness_check", status: "active" },
  { event: "deployment_requirements_completed", action: "set_ready_for_deployment", status: "active" },
  { event: "employee_activated", action: "create_employee_workspace", status: "active" },
  { event: "contract_nearing_expiry", action: "create_compliance_alert", status: "active" },
  { event: "hr_request_overdue", action: "escalate_request", status: "under_review" },
  { event: "timesheet_approved", action: "mark_payroll_input_ready", status: "active" },
];

export const activationCreates = [
  "employee_profile",
  "employee_id",
  "user_account",
  "client_assignment",
  "workspace_membership",
  "reporting_relationship",
  "role_permissions",
  "compliance_schedule",
  "performance_cycle",
  "payroll_workflow_profile",
];
