/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HrRouteImport } from './routes/hr'
import { Route as HrIndexRouteImport } from './routes/hr.index'
import { Route as HrAnalyticsRouteImport } from './routes/hr.analytics'
import { Route as HrAttendanceRouteImport } from './routes/hr.attendance'
import { Route as HrCandidatesRouteImport } from './routes/hr.candidates'
import { Route as HrClientPortalRouteImport } from './routes/hr.client-portal'
import { Route as HrComplianceRouteImport } from './routes/hr.compliance'
import { Route as HrDeploymentReadinessRouteImport } from './routes/hr.deployment-readiness'
import { Route as HrDeploymentsRouteImport } from './routes/hr.deployments'
import { Route as HrEmployeePortalRouteImport } from './routes/hr.employee-portal'
import { Route as HrEmployeesRouteImport } from './routes/hr.employees'
import { Route as HrInterviewsRouteImport } from './routes/hr.interviews'
import { Route as HrLeaveRouteImport } from './routes/hr.leave'
import { Route as HrOffersRouteImport } from './routes/hr.offers'
import { Route as HrOnboardingRouteImport } from './routes/hr.onboarding'
import { Route as HrPayrollRouteImport } from './routes/hr.payroll'
import { Route as HrPerformanceRouteImport } from './routes/hr.performance'
import { Route as HrServiceDeskRouteImport } from './routes/hr.service-desk'
import { Route as HrSoniaRouteImport } from './routes/hr.sonia'
import { Route as HrTimesheetsRouteImport } from './routes/hr.timesheets'
import { Route as HrVacanciesRouteImport } from './routes/hr.vacancies'
import { Route as HrVerificationRouteImport } from './routes/hr.verification'
import { Route as HrWorkforceRequestsRouteImport } from './routes/hr.workforce-requests'
import { Route as HrSettingsIndexRouteImport } from './routes/hr.settings.index'
import { Route as HrSettingsWorkflowsRouteImport } from './routes/hr.settings.workflows'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const HrIndexRoute = HrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HrRoute,
} as any)
const HrAnalyticsRoute = HrAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => HrRoute,
} as any)
const HrAttendanceRoute = HrAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => HrRoute,
} as any)
const HrCandidatesRoute = HrCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => HrRoute,
} as any)
const HrClientPortalRoute = HrClientPortalRouteImport.update({
  id: '/client-portal',
  path: '/client-portal',
  getParentRoute: () => HrRoute,
} as any)
const HrComplianceRoute = HrComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => HrRoute,
} as any)
const HrDeploymentReadinessRoute = HrDeploymentReadinessRouteImport.update({
  id: '/deployment-readiness',
  path: '/deployment-readiness',
  getParentRoute: () => HrRoute,
} as any)
const HrDeploymentsRoute = HrDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => HrRoute,
} as any)
const HrEmployeePortalRoute = HrEmployeePortalRouteImport.update({
  id: '/employee-portal',
  path: '/employee-portal',
  getParentRoute: () => HrRoute,
} as any)
const HrEmployeesRoute = HrEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => HrRoute,
} as any)
const HrInterviewsRoute = HrInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => HrRoute,
} as any)
const HrLeaveRoute = HrLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => HrRoute,
} as any)
const HrOffersRoute = HrOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => HrRoute,
} as any)
const HrOnboardingRoute = HrOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => HrRoute,
} as any)
const HrPayrollRoute = HrPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => HrRoute,
} as any)
const HrPerformanceRoute = HrPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => HrRoute,
} as any)
const HrServiceDeskRoute = HrServiceDeskRouteImport.update({
  id: '/service-desk',
  path: '/service-desk',
  getParentRoute: () => HrRoute,
} as any)
const HrSoniaRoute = HrSoniaRouteImport.update({
  id: '/sonia',
  path: '/sonia',
  getParentRoute: () => HrRoute,
} as any)
const HrTimesheetsRoute = HrTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => HrRoute,
} as any)
const HrVacanciesRoute = HrVacanciesRouteImport.update({
  id: '/vacancies',
  path: '/vacancies',
  getParentRoute: () => HrRoute,
} as any)
const HrVerificationRoute = HrVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => HrRoute,
} as any)
const HrWorkforceRequestsRoute = HrWorkforceRequestsRouteImport.update({
  id: '/workforce-requests',
  path: '/workforce-requests',
  getParentRoute: () => HrRoute,
} as any)
const HrSettingsIndexRoute = HrSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => HrRoute,
} as any)
const HrSettingsWorkflowsRoute = HrSettingsWorkflowsRouteImport.update({
  id: '/settings/workflows',
  path: '/settings/workflows',
  getParentRoute: () => HrRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hr': typeof HrRouteWithChildren
  '/hr/analytics': typeof HrAnalyticsRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/candidates': typeof HrCandidatesRoute
  '/hr/client-portal': typeof HrClientPortalRoute
  '/hr/compliance': typeof HrComplianceRoute
  '/hr/deployment-readiness': typeof HrDeploymentReadinessRoute
  '/hr/deployments': typeof HrDeploymentsRoute
  '/hr/employee-portal': typeof HrEmployeePortalRoute
  '/hr/employees': typeof HrEmployeesRoute
  '/hr/interviews': typeof HrInterviewsRoute
  '/hr/leave': typeof HrLeaveRoute
  '/hr/offers': typeof HrOffersRoute
  '/hr/onboarding': typeof HrOnboardingRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/performance': typeof HrPerformanceRoute
  '/hr/service-desk': typeof HrServiceDeskRoute
  '/hr/sonia': typeof HrSoniaRoute
  '/hr/timesheets': typeof HrTimesheetsRoute
  '/hr/vacancies': typeof HrVacanciesRoute
  '/hr/verification': typeof HrVerificationRoute
  '/hr/workforce-requests': typeof HrWorkforceRequestsRoute
  '/hr/': typeof HrIndexRoute
  '/hr/settings/workflows': typeof HrSettingsWorkflowsRoute
  '/hr/settings/': typeof HrSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hr/analytics': typeof HrAnalyticsRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/candidates': typeof HrCandidatesRoute
  '/hr/client-portal': typeof HrClientPortalRoute
  '/hr/compliance': typeof HrComplianceRoute
  '/hr/deployment-readiness': typeof HrDeploymentReadinessRoute
  '/hr/deployments': typeof HrDeploymentsRoute
  '/hr/employee-portal': typeof HrEmployeePortalRoute
  '/hr/employees': typeof HrEmployeesRoute
  '/hr/interviews': typeof HrInterviewsRoute
  '/hr/leave': typeof HrLeaveRoute
  '/hr/offers': typeof HrOffersRoute
  '/hr/onboarding': typeof HrOnboardingRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/performance': typeof HrPerformanceRoute
  '/hr/service-desk': typeof HrServiceDeskRoute
  '/hr/sonia': typeof HrSoniaRoute
  '/hr/timesheets': typeof HrTimesheetsRoute
  '/hr/vacancies': typeof HrVacanciesRoute
  '/hr/verification': typeof HrVerificationRoute
  '/hr/workforce-requests': typeof HrWorkforceRequestsRoute
  '/hr': typeof HrIndexRoute
  '/hr/settings/workflows': typeof HrSettingsWorkflowsRoute
  '/hr/settings': typeof HrSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hr': typeof HrRouteWithChildren
  '/hr/analytics': typeof HrAnalyticsRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/candidates': typeof HrCandidatesRoute
  '/hr/client-portal': typeof HrClientPortalRoute
  '/hr/compliance': typeof HrComplianceRoute
  '/hr/deployment-readiness': typeof HrDeploymentReadinessRoute
  '/hr/deployments': typeof HrDeploymentsRoute
  '/hr/employee-portal': typeof HrEmployeePortalRoute
  '/hr/employees': typeof HrEmployeesRoute
  '/hr/interviews': typeof HrInterviewsRoute
  '/hr/leave': typeof HrLeaveRoute
  '/hr/offers': typeof HrOffersRoute
  '/hr/onboarding': typeof HrOnboardingRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/performance': typeof HrPerformanceRoute
  '/hr/service-desk': typeof HrServiceDeskRoute
  '/hr/sonia': typeof HrSoniaRoute
  '/hr/timesheets': typeof HrTimesheetsRoute
  '/hr/vacancies': typeof HrVacanciesRoute
  '/hr/verification': typeof HrVerificationRoute
  '/hr/workforce-requests': typeof HrWorkforceRequestsRoute
  '/hr/': typeof HrIndexRoute
  '/hr/settings/workflows': typeof HrSettingsWorkflowsRoute
  '/hr/settings/': typeof HrSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hr'
    | '/hr/analytics'
    | '/hr/attendance'
    | '/hr/candidates'
    | '/hr/client-portal'
    | '/hr/compliance'
    | '/hr/deployment-readiness'
    | '/hr/deployments'
    | '/hr/employee-portal'
    | '/hr/employees'
    | '/hr/interviews'
    | '/hr/leave'
    | '/hr/offers'
    | '/hr/onboarding'
    | '/hr/payroll'
    | '/hr/performance'
    | '/hr/service-desk'
    | '/hr/sonia'
    | '/hr/timesheets'
    | '/hr/vacancies'
    | '/hr/verification'
    | '/hr/workforce-requests'
    | '/hr/'
    | '/hr/settings/workflows'
    | '/hr/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hr/analytics'
    | '/hr/attendance'
    | '/hr/candidates'
    | '/hr/client-portal'
    | '/hr/compliance'
    | '/hr/deployment-readiness'
    | '/hr/deployments'
    | '/hr/employee-portal'
    | '/hr/employees'
    | '/hr/interviews'
    | '/hr/leave'
    | '/hr/offers'
    | '/hr/onboarding'
    | '/hr/payroll'
    | '/hr/performance'
    | '/hr/service-desk'
    | '/hr/sonia'
    | '/hr/timesheets'
    | '/hr/vacancies'
    | '/hr/verification'
    | '/hr/workforce-requests'
    | '/hr'
    | '/hr/settings/workflows'
    | '/hr/settings'
  id:
    | '__root__'
    | '/'
    | '/hr'
    | '/hr/analytics'
    | '/hr/attendance'
    | '/hr/candidates'
    | '/hr/client-portal'
    | '/hr/compliance'
    | '/hr/deployment-readiness'
    | '/hr/deployments'
    | '/hr/employee-portal'
    | '/hr/employees'
    | '/hr/interviews'
    | '/hr/leave'
    | '/hr/offers'
    | '/hr/onboarding'
    | '/hr/payroll'
    | '/hr/performance'
    | '/hr/service-desk'
    | '/hr/sonia'
    | '/hr/timesheets'
    | '/hr/vacancies'
    | '/hr/verification'
    | '/hr/workforce-requests'
    | '/hr/'
    | '/hr/settings/workflows'
    | '/hr/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HrRoute: typeof HrRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/': {
      id: '/hr/'
      path: '/'
      fullPath: '/hr/'
      preLoaderRoute: typeof HrIndexRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/analytics': {
      id: '/hr/analytics'
      path: '/analytics'
      fullPath: '/hr/analytics'
      preLoaderRoute: typeof HrAnalyticsRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/attendance': {
      id: '/hr/attendance'
      path: '/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof HrAttendanceRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/candidates': {
      id: '/hr/candidates'
      path: '/candidates'
      fullPath: '/hr/candidates'
      preLoaderRoute: typeof HrCandidatesRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/client-portal': {
      id: '/hr/client-portal'
      path: '/client-portal'
      fullPath: '/hr/client-portal'
      preLoaderRoute: typeof HrClientPortalRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/compliance': {
      id: '/hr/compliance'
      path: '/compliance'
      fullPath: '/hr/compliance'
      preLoaderRoute: typeof HrComplianceRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/deployment-readiness': {
      id: '/hr/deployment-readiness'
      path: '/deployment-readiness'
      fullPath: '/hr/deployment-readiness'
      preLoaderRoute: typeof HrDeploymentReadinessRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/deployments': {
      id: '/hr/deployments'
      path: '/deployments'
      fullPath: '/hr/deployments'
      preLoaderRoute: typeof HrDeploymentsRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/employee-portal': {
      id: '/hr/employee-portal'
      path: '/employee-portal'
      fullPath: '/hr/employee-portal'
      preLoaderRoute: typeof HrEmployeePortalRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/employees': {
      id: '/hr/employees'
      path: '/employees'
      fullPath: '/hr/employees'
      preLoaderRoute: typeof HrEmployeesRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/interviews': {
      id: '/hr/interviews'
      path: '/interviews'
      fullPath: '/hr/interviews'
      preLoaderRoute: typeof HrInterviewsRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/leave': {
      id: '/hr/leave'
      path: '/leave'
      fullPath: '/hr/leave'
      preLoaderRoute: typeof HrLeaveRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/offers': {
      id: '/hr/offers'
      path: '/offers'
      fullPath: '/hr/offers'
      preLoaderRoute: typeof HrOffersRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/onboarding': {
      id: '/hr/onboarding'
      path: '/onboarding'
      fullPath: '/hr/onboarding'
      preLoaderRoute: typeof HrOnboardingRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/payroll': {
      id: '/hr/payroll'
      path: '/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof HrPayrollRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/performance': {
      id: '/hr/performance'
      path: '/performance'
      fullPath: '/hr/performance'
      preLoaderRoute: typeof HrPerformanceRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/service-desk': {
      id: '/hr/service-desk'
      path: '/service-desk'
      fullPath: '/hr/service-desk'
      preLoaderRoute: typeof HrServiceDeskRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/sonia': {
      id: '/hr/sonia'
      path: '/sonia'
      fullPath: '/hr/sonia'
      preLoaderRoute: typeof HrSoniaRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/timesheets': {
      id: '/hr/timesheets'
      path: '/timesheets'
      fullPath: '/hr/timesheets'
      preLoaderRoute: typeof HrTimesheetsRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/vacancies': {
      id: '/hr/vacancies'
      path: '/vacancies'
      fullPath: '/hr/vacancies'
      preLoaderRoute: typeof HrVacanciesRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/verification': {
      id: '/hr/verification'
      path: '/verification'
      fullPath: '/hr/verification'
      preLoaderRoute: typeof HrVerificationRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/workforce-requests': {
      id: '/hr/workforce-requests'
      path: '/workforce-requests'
      fullPath: '/hr/workforce-requests'
      preLoaderRoute: typeof HrWorkforceRequestsRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/settings/': {
      id: '/hr/settings/'
      path: '/settings'
      fullPath: '/hr/settings/'
      preLoaderRoute: typeof HrSettingsIndexRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/settings/workflows': {
      id: '/hr/settings/workflows'
      path: '/settings/workflows'
      fullPath: '/hr/settings/workflows'
      preLoaderRoute: typeof HrSettingsWorkflowsRouteImport
      parentRoute: typeof HrRoute
    }
  }
}

interface HrRouteChildren {
  HrAnalyticsRoute: typeof HrAnalyticsRoute
  HrAttendanceRoute: typeof HrAttendanceRoute
  HrCandidatesRoute: typeof HrCandidatesRoute
  HrClientPortalRoute: typeof HrClientPortalRoute
  HrComplianceRoute: typeof HrComplianceRoute
  HrDeploymentReadinessRoute: typeof HrDeploymentReadinessRoute
  HrDeploymentsRoute: typeof HrDeploymentsRoute
  HrEmployeePortalRoute: typeof HrEmployeePortalRoute
  HrEmployeesRoute: typeof HrEmployeesRoute
  HrInterviewsRoute: typeof HrInterviewsRoute
  HrLeaveRoute: typeof HrLeaveRoute
  HrOffersRoute: typeof HrOffersRoute
  HrOnboardingRoute: typeof HrOnboardingRoute
  HrPayrollRoute: typeof HrPayrollRoute
  HrPerformanceRoute: typeof HrPerformanceRoute
  HrServiceDeskRoute: typeof HrServiceDeskRoute
  HrSoniaRoute: typeof HrSoniaRoute
  HrTimesheetsRoute: typeof HrTimesheetsRoute
  HrVacanciesRoute: typeof HrVacanciesRoute
  HrVerificationRoute: typeof HrVerificationRoute
  HrWorkforceRequestsRoute: typeof HrWorkforceRequestsRoute
  HrIndexRoute: typeof HrIndexRoute
  HrSettingsWorkflowsRoute: typeof HrSettingsWorkflowsRoute
  HrSettingsIndexRoute: typeof HrSettingsIndexRoute
}

const HrRouteChildren: HrRouteChildren = {
  HrAnalyticsRoute: HrAnalyticsRoute,
  HrAttendanceRoute: HrAttendanceRoute,
  HrCandidatesRoute: HrCandidatesRoute,
  HrClientPortalRoute: HrClientPortalRoute,
  HrComplianceRoute: HrComplianceRoute,
  HrDeploymentReadinessRoute: HrDeploymentReadinessRoute,
  HrDeploymentsRoute: HrDeploymentsRoute,
  HrEmployeePortalRoute: HrEmployeePortalRoute,
  HrEmployeesRoute: HrEmployeesRoute,
  HrInterviewsRoute: HrInterviewsRoute,
  HrLeaveRoute: HrLeaveRoute,
  HrOffersRoute: HrOffersRoute,
  HrOnboardingRoute: HrOnboardingRoute,
  HrPayrollRoute: HrPayrollRoute,
  HrPerformanceRoute: HrPerformanceRoute,
  HrServiceDeskRoute: HrServiceDeskRoute,
  HrSoniaRoute: HrSoniaRoute,
  HrTimesheetsRoute: HrTimesheetsRoute,
  HrVacanciesRoute: HrVacanciesRoute,
  HrVerificationRoute: HrVerificationRoute,
  HrWorkforceRequestsRoute: HrWorkforceRequestsRoute,
  HrIndexRoute: HrIndexRoute,
  HrSettingsWorkflowsRoute: HrSettingsWorkflowsRoute,
  HrSettingsIndexRoute: HrSettingsIndexRoute,
}

const HrRouteWithChildren = HrRoute._addFileChildren(HrRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HrRoute: HrRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
